services:
  traefik:
    image: traefik:3.6.10
    command:
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - ./deploy/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro

  phpsage-web:
    environment:
      PHPSAGE_PUBLIC_HOST: ${PHPSAGE_PUBLIC_HOST}

  api-docs:
    environment:
      BASE_URL: /docs