tls:
  certificates:
    - certFile: /etc/traefik/certs/origin.crt
      keyFile: /etc/traefik/certs/origin.key

http:
  routers:
    phpsage-docs:
      rule: PathPrefix(`/docs`)
      entryPoints:
        - websecure
      service: phpsage-docs
      tls: {}

    phpsage-web:
      rule: PathPrefix(`/`)
      entryPoints:
        - websecure
      service: phpsage-web
      tls: {}

    phpsage-api:
      rule: PathPrefix(`/api`) || Path(`/healthz`)
      entryPoints:
        - websecure
      service: phpsage-api
      tls: {}

  services:
    phpsage-docs:
      loadBalancer:
        servers:
          - url: http://api-docs:8080

    phpsage-web:
      loadBalancer:
        servers:
          - url: http://phpsage-web:5173

    phpsage-api:
      loadBalancer:
        servers:
          - url: http://phpsage-server:8080